
project_id = "axigtrmaxhetyfzjjdve"

[functions.manage-user-roles]
verify_jwt = true

[functions.refresh-quickbooks-tokens]
verify_jwt = false

[functions.create-business-user]
verify_jwt = false

[functions.create-shipday-order]
verify_jwt = false

[functions.delete-shipday-order]
verify_jwt = false

[functions.generate-tracking-numbers]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.shipday-webhook]
verify_jwt = false

[functions.orders]
verify_jwt = false

[functions.quickbooks-oauth-callback]
verify_jwt = false

[functions.send-timeslip-whatsapp]
verify_jwt = false

[functions.shopify-webhook]
verify_jwt = false
