project_id = "axigtrmaxhetyfzjjdve"

[functions.calculate-weekly-bonuses]
verify_jwt = false

[functions.trigger-webhook]
verify_jwt = false

[functions.manage-user-roles]
verify_jwt = true

[functions.refresh-quickbooks-tokens]
verify_jwt = false

[functions.create-business-user]
verify_jwt = false

[functions.create-shipday-order]
verify_jwt = false

[functions.delete-shipday-order]
verify_jwt = false

[functions.generate-tracking-numbers]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.shipday-webhook]
verify_jwt = false

[functions.orders]
verify_jwt = false

[functions.quickbooks-oauth-callback]
verify_jwt = false

[functions.send-timeslip-whatsapp]
verify_jwt = false

[functions.shopify-webhook]
verify_jwt = false

[functions.create-webhook-config]
verify_jwt = false

[functions.create-quickbooks-bill]
verify_jwt = false

[functions.create-optimoroute-order]
verify_jwt = false

[functions.sync-orders-to-optimoroute]
verify_jwt = false

[functions.query-database-completed-jobs]
verify_jwt = false

[functions.send-route-report]
verify_jwt = false
